name: Run Selenium Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Set up Java
        uses: actions/setup-java@v3  
          java-version: '11'
          distribution: 'temurin'

      - name: Install Dependencies and Run Selenium Tests
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          mvn clean test
